<a href="https://colab.research.google.com/github/hector1994/TT-DA-95-GIT-EXPERIMENT/blob/main/GITHUB_Mini_experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
ruta = "https://media.githubusercontent.com/media/hector1994/e_commerce_funnel_data_generator/refs/heads/master/data_clase_sql_final.csv"

In [3]:
df = pd.read_csv(ruta)
df.head(10)

,event_type_id,user_id,session_id,event_name,event_timestamp,time_zone,country,device,traffic_source,category,sku,cart_id,payment_method,units,amount
0,4,11053828,SESS-11053828-4,scroll,2026-01-11 01:10:31,UTC-5,Colombia,Desktop,Facebook,Clothing,SKU-2009,NaN,NaN,0,0.00
1,1,11031713,SESS-11031713-2,home_page,2026-01-14 14:00:40,UTC-6,México,Tablet,Email,NaN,NaN,NaN,NaN,0,0.00
2,2,11050906,SESS-11050906-3,log_in,2026-01-15 07:01:05,UTC-6,México,Tablet,Google,NaN,NaN,NaN,NaN,0,0.00
3,1,11128908,SESS-11128908-2,home_page,2026-01-27 22:00:17,UTC-3,Chile,Mobile,Facebook,NaN,NaN,NaN,NaN,0,0.00
4,5,11131545,SESS-11131545-3,click_product,2026-01-16 18:15:16,UTC-3,Argentina,Tablet,Google,Clothing,SKU-3798,NaN,NaN,0,0.00
5,3,11116039,SESS-11116039-4,page_view,2026-01-31 11:05:42,UTC-3,Argentina,Tablet,Facebook,Electronics,SKU-1823,NaN,NaN,0,0.00
6,6,11154443,SESS-11154443-2,add_to_cart,2026-01-06 18:15:18,UTC-6,México,Tablet,Google,Home,SKU-1475,CART-185435,NaN,1,491.69
7,3,11078425,SESS-11078425-3,page_view,2026-01-11 16:07:03,UTC+1,España,Desktop,Email,Home,SKU-4663,NaN,NaN,0,0.00
8,3,11134697,SESS-11134697-1,page_view,2026-01-25 15:07:52,UTC-3,Chile,Desktop,Facebook,Clothing,SKU-2644,NaN,NaN,0,0.00
9,2,11122720,SESS-11122720-1,log_in,2026-01-18 10:01:37,UTC-6,México,Mobile,Facebook,NaN,NaN,NaN,NaN,0,0.00

In [4]:
df.columns

Index(['event_type_id', 'user_id', 'session_id', 'event_name',
       'event_timestamp', 'time_zone', 'country', 'device', 'traffic_source',
       'category', 'sku', 'cart_id', 'payment_method', 'units', 'amount'],
      dtype='object')

In [5]:
df.dtypes

event_type_id        int64
user_id              int64
session_id          object
event_name          object
event_timestamp     object
time_zone           object
country             object
device              object
traffic_source      object
category            object
sku                 object
cart_id             object
payment_method      object
units                int64
amount             float64
dtype: object

In [6]:
df.describe()

       event_type_id       user_id         units        amount
count   1.550127e+06  1.550127e+06  1.550127e+06  1.550127e+06
mean    3.086090e+00  1.108147e+07  1.336084e-01  3.472883e+01
std     1.942771e+00  4.701170e+04  3.402312e-01  1.018810e+02
min     1.000000e+00  1.100000e+07  0.000000e+00  0.000000e+00
25%     1.000000e+00  1.104079e+07  0.000000e+00  0.000000e+00
50%     3.000000e+00  1.108156e+07  0.000000e+00  0.000000e+00
75%     4.000000e+00  1.112226e+07  0.000000e+00  0.000000e+00
max     9.000000e+00  1.116267e+07  1.000000e+00  5.000000e+02

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1550127 entries, 0 to 1550126
Data columns (total 15 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   event_type_id    1550127 non-null  int64
 1   user_id          1550127 non-null  int64
 2   session_id       1550127 non-null  object
 3   event_name       1550127 non-null  object
 4   event_timestamp  1550127 non-null  object
 5   time_zone        1550127 non-null  object
 6   country          1550127 non-null  object
 7   device           1550127 non-null  object
 8   traffic_source   1550127 non-null  object
 9   category         818033 non-null   object
 10  sku              818033 non-null   object
 11  cart_id          207110 non-null   object
 12  payment_method   12169 non-null    object
 13  units            1550127 non-null  int64
 14  amount           1550127 non-null  float64
dtypes: float64(1), int64(3), object(11)
memory usage: 177.4+ MB

In [8]:
df['columna_nueva'] = 2*df['units']

In [9]:
df.head()

,event_type_id,user_id,session_id,event_name,event_timestamp,time_zone,country,device,traffic_source,category,sku,cart_id,payment_method,units,amount,columna_nueva
0,4,11053828,SESS-11053828-4,scroll,2026-01-11 01:10:31,UTC-5,Colombia,Desktop,Facebook,Clothing,SKU-2009,NaN,NaN,0,0.0,0
1,1,11031713,SESS-11031713-2,home_page,2026-01-14 14:00:40,UTC-6,México,Tablet,Email,NaN,NaN,NaN,NaN,0,0.0,0
2,2,11050906,SESS-11050906-3,log_in,2026-01-15 07:01:05,UTC-6,México,Tablet,Google,NaN,NaN,NaN,NaN,0,0.0,0
3,1,11128908,SESS-11128908-2,home_page,2026-01-27 22:00:17,UTC-3,Chile,Mobile,Facebook,NaN,NaN,NaN,NaN,0,0.0,0
4,5,11131545,SESS-11131545-3,click_product,2026-01-16 18:15:16,UTC-3,Argentina,Tablet,Google,Clothing,SKU-3798,NaN,NaN,0,0.0,0

In [10]:
df[df['columna_nueva']>0].head()

,event_type_id,user_id,session_id,event_name,event_timestamp,time_zone,country,device,traffic_source,category,sku,cart_id,payment_method,units,amount,columna_nueva
6,6,11154443,SESS-11154443-2,add_to_cart,2026-01-06 18:15:18,UTC-6,México,Tablet,Google,Home,SKU-1475,CART-185435,NaN,1,491.69,2
12,7,11110873,SESS-11110873-3,begin_checkout,2026-01-29 12:15:52,UTC-3,Argentina,Desktop,Facebook,Clothing,SKU-2899,CART-569165,NaN,1,227.18,2
43,6,11143111,SESS-11143111-1,add_to_cart,2026-01-17 01:11:50,UTC-5,Colombia,Tablet,Direct,Home,SKU-4043,CART-928312,NaN,1,97.88,2
65,6,11105886,SESS-11105886-1,add_to_cart,2026-01-27 04:13:08,UTC-5,Colombia,Mobile,Google,Home,SKU-3787,CART-315511,NaN,1,411.02,2
67,6,11049085,SESS-11049085-3,add_to_cart,2026-01-25 19:07:49,UTC+1,España,Mobile,Direct,Electronics,SKU-3559,CART-534117,NaN,1,277.61,2