<a href="https://colab.research.google.com/github/hector1994/TT-DA-95-GIT-EXPERIMENT/blob/main/GITHUB_Mini_experiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
ruta = "https://media.githubusercontent.com/media/hector1994/e_commerce_funnel_data_generator/refs/heads/master/data_clase_sql_final.csv"

In [3]:
df = pd.read_csv(ruta)
df.head(10)

,event_type_id,user_id,session_id,event_name,event_timestamp,time_zone,country,device,traffic_source,category,sku,cart_id,payment_method,units,amount
0,4,11053828,SESS-11053828-4,scroll,2026-01-11 01:10:31,UTC-5,Colombia,Desktop,Facebook,Clothing,SKU-2009,NaN,NaN,0,0.00
1,1,11031713,SESS-11031713-2,home_page,2026-01-14 14:00:40,UTC-6,México,Tablet,Email,NaN,NaN,NaN,NaN,0,0.00
2,2,11050906,SESS-11050906-3,log_in,2026-01-15 07:01:05,UTC-6,México,Tablet,Google,NaN,NaN,NaN,NaN,0,0.00
3,1,11128908,SESS-11128908-2,home_page,2026-01-27 22:00:17,UTC-3,Chile,Mobile,Facebook,NaN,NaN,NaN,NaN,0,0.00
4,5,11131545,SESS-11131545-3,click_product,2026-01-16 18:15:16,UTC-3,Argentina,Tablet,Google,Clothing,SKU-3798,NaN,NaN,0,0.00
5,3,11116039,SESS-11116039-4,page_view,2026-01-31 11:05:42,UTC-3,Argentina,Tablet,Facebook,Electronics,SKU-1823,NaN,NaN,0,0.00
6,6,11154443,SESS-11154443-2,add_to_cart,2026-01-06 18:15:18,UTC-6,México,Tablet,Google,Home,SKU-1475,CART-185435,NaN,1,491.69
7,3,11078425,SESS-11078425-3,page_view,2026-01-11 16:07:03,UTC+1,España,Desktop,Email,Home,SKU-4663,NaN,NaN,0,0.00
8,3,11134697,SESS-11134697-1,page_view,2026-01-25 15:07:52,UTC-3,Chile,Desktop,Facebook,Clothing,SKU-2644,NaN,NaN,0,0.00
9,2,11122720,SESS-11122720-1,log_in,2026-01-18 10:01:37,UTC-6,México,Mobile,Facebook,NaN,NaN,NaN,NaN,0,0.00

In [4]:
df.columns

Index(['event_type_id', 'user_id', 'session_id', 'event_name',
       'event_timestamp', 'time_zone', 'country', 'device', 'traffic_source',
       'category', 'sku', 'cart_id', 'payment_method', 'units', 'amount'],
      dtype='object')

In [5]:
df.dtypes

event_type_id        int64
user_id              int64
session_id          object
event_name          object
event_timestamp     object
time_zone           object
country             object
device              object
traffic_source      object
category            object
sku                 object
cart_id             object
payment_method      object
units                int64
amount             float64
dtype: object